Dns dock version
greg0ire/dockerony pull request #45
Opened 2016-11-22 08:41 UTC by jngermon

With docker-compose write in version 2 and dnsdock:latest, the system is not working. Dnsdock:latest do not recognonize container IP. We have to use the "amd64-1.13.1" version (5 months younger) to fix it.

2016-11-22 09:12 UTC, greg0ire requested changes

2016-11-22 09:12 UTC, greg0ire commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
Is it outline or oneline? Pick one ;)

2016-11-22 09:12 UTC, greg0ire commented on bin/docker-outline-dns
> +
Please remove line 10.

2016-11-22 09:12 UTC, greg0ire commented on bin/docker-outline-dns
> +    cut --delimiter=\  --fields=7|cut --delimiter=/ --fields=1)
`--delimiter=' '` is maybe easier to understand

2016-12-01 08:20 UTC, jngermon commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
it's "oneline" option for "ip" command"  => output one record per line

2016-12-01 08:23 UTC, jngermon commented on bin/docker-outline-dns
> +    cut --delimiter=\  --fields=7|cut --delimiter=/ --fields=1)
Ok I will do ti

2016-12-01 08:50 UTC, greg0ire commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
Ok, but the file is named docker-outline-dns… what does that refer to?

2017-02-23 14:30 UTC, greg0ire commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
ping @jngermon

2017-04-03 09:31 UTC, jngermon commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
Apology
The two files are about two differents things.
For the dns_dock version, only the change in docker-init is requiered.
The file docker-outline-dns is to enable use this system on outline mode (without connection the network manager does not link DNSDOCK as DNS server.
Do you want two differents Pull requests ? (or just one about docker-compose v2 ?)

2017-04-03 09:37 UTC, greg0ire commented on bin/docker-outline-dns
> +docker_ip=$(ip -family inet -oneline addr show docker0|\
Ooooh ok I think you mean "offline mode". Can you change that? Also, one PR is fine, as long as you make 2 commits :)

2018-02-27 13:37 UTC, greg0ire approved these changes

2018-02-27 13:42 UTC, merged

2018-02-27 13:42 UTC, greg0ire commented
Totally forgot about this PR, thanks @jngermon !